FROM ubuntu:22.04
RUN apt update && apt install wget -y
RUN wget -c https://golang.org/dl/go1.22.12.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.12.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin:/root/go/bin
RUN go version

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN dlv version

# Deploy the application binary into a lean image
#FROM ubuntu:latest AS build-release-stage
# FROM ubuntu:22.04

# Settings for all images
ENV TIMEZONE=America/New_York

# Run system updates
RUN apt-get update && apt-get -y upgrade

# Set time zone
RUN ln -sn /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && echo ${TIMEZONE} > /etc/timezone \
    && apt-get -y install tzdata curl

# Set locale
RUN apt-get -y install locales \
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 LC_MESSAGES=POSIX

# Install system packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install munge \
                   slurm-wlm

# Slurm configuration
COPY docker/slurm.conf /etc/slurm/slurm.conf
RUN mkdir -p /var/spool/slurmctld \
    && chown slurm:slurm /var/spool/slurmctld

# Startup configuration
COPY docker/startup.sh /etc/startup.sh
RUN chmod 555 /etc/startup.sh

# WORKDIR /root

# COPY --from=build-stage /app/bin/slurm-sidecar /sidecar/slurm-sidecar
# COPY --from=build-stage /go/bin/dlv /dlv

ENV SLURMCONFIGPATH=/root/SlurmConfig.yaml

RUN apt-get update && apt-get install -y software-properties-common \
 && add-apt-repository -y ppa:apptainer/ppa \
 && apt-get install -y apptainer

RUN <<EOF
    arch=$(dpkg --print-architecture)
    curl -fSsL -O https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot_3.5.0-1_${arch}.deb
    curl -fSsL -O https://github.com/NVIDIA/enroot/releases/download/v3.5.0/enroot+caps_3.5.0-1_${arch}.deb
    apt install -y ./*.deb
EOF
RUN mkdir -p /cvmfs/grid.cern.ch/etc/grid-security

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -o bin/slurm-sidecar cmd/main.go

CMD ["/bin/sh", "-c", "/etc/startup.sh && SHARED_FS=true dlv --listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec /app/bin/slurm-sidecar"]
